openapi: 3.0.1
info:
  title: checkout-demo-codeigniter
  description: checkout-demo-codeigniter
  x-cortex-tag: checkout-demo-codeigniter
  x-cortex-git:
    github:
      repository: xendit/checkout-demo-codeigniter
  x-cortex-owners:
  - type: GROUP
    name: xendit/api-full-time